name: 🐛 Bug Report
description: Report an issue that should be fixed.
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve flowimds!

        If you need usage support rather than reporting a bug, please start a thread in [GitHub Discussions](https://github.com/mori-318/flowimds/discussions).

        Please include as much detail as possible so we can reproduce and fix the issue quickly.
  - type: input
    id: version
    attributes:
      label: Which version of flowimds are you using?
      placeholder: 0.0.0
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: What platform or runtime are you using? (Include versions if possible)
      placeholder: macOS 14.1, Python 3.11.6, uv 0.4.20, etc.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: What steps can reproduce the bug?
      description: Explain the bug and provide a minimal reproducible example if possible.
      placeholder: |
        1. Run `...`
        2. Execute the pipeline with ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What actually happened?
      description: Include error messages or stack traces if available.
      placeholder: e.g., `ValueError: ...`
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Share logs, screenshots, or other details that might help.
      placeholder: Relevant logs, screenshots, or links
    validations:
      required: false
