name: 🚀 Feature Request
description: Suggest an idea, feature, or enhancement.
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an idea. It helps make flowimds better.
  - type: textarea
    id: summary
    attributes:
      label: What feature are you proposing?
      description: Provide a clear description of what you want to happen.
      placeholder: e.g., Add a CLI option to automate image batch processing
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature valuable?
      description: Explain the problem this feature would solve or the benefit it provides.
      placeholder: |
        - Current workflow requires manual steps...
        - This would support use case Y...
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Do you have a proposed solution?
      description: Outline potential implementation ideas, API design, or examples.
      placeholder: Describe how you imagine the feature working.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Include related issues, references, or screenshots if helpful.
      placeholder: Relevant references or URLs
    validations:
      required: false
