name: Feature request
description: Use this template to suggest a new feature or improvement.
title: "[Feature] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion. Please explain the background and goal clearly.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Summarize the proposal in one sentence.
      placeholder: e.g., Add a CLI option to automate image batch processing
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Describe the current problem and the goal you want to achieve.
      placeholder: |
        - Manual workflow X is time-consuming
        - We want to support use case Y
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the solution or feature in detail.
      placeholder: Outline desired behavior, specifications, or implementation ideas
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Share any alternative approaches considered.
      placeholder: e.g., Control via environment variables
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Provide related issues, documents, or reference links.
      placeholder: Relevant resources or URLs
    validations:
      required: false
